# Build a JSON export from a karas database
# It needs a karas.sqlite3 database generated by karaoke mugen 


DB=$1

sqlite3 $DB "SELECT '{\"karas\":[' || group_concat(json_object('kid',kid,'titl
e',title,'duration',videolength,'audiogain',gain,'year',year,'videofile',videofi
le,'dateadded',created_at,'datemodif',modified_at,'order',songorder,'serie',seri
e,'singer',singer,'type',songtype,'creator',creator,'lang',language,'author',aut
hor,'tags',misc,'songwriter',songwriter)) || ']}' FROM all_karas;"